// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Reservation struct {
	ID        int32
	RoomID    int32
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
}

type Room struct {
	ID   int32
	Name string
}
